# Generated by Django 5.2 on 2025-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client'), ('owner', 'owner')], max_length=40),
        ),
    ]
